# Generated by Django 5.2.5 on 2025-09-19 13:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('no_of_listings', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('looking_to', models.CharField(choices=[('rent', 'Rent'), ('sell', 'Sell'), ('pg', 'PG')], max_length=10)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('independent_house', 'Independent House'), ('duplex', 'Duplex'), ('independent_floor', 'Independent Floor'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('studio', 'Studio'), ('farm_house', 'Farm House')], max_length=30)),
                ('building', models.CharField(blank=True, max_length=250, verbose_name='Building / Society / Project')),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('bhk', models.CharField(choices=[('1rk', '1 RK'), ('1', '1 BHK'), ('1.5', '1.5 BHK'), ('2', '2 BHK'), ('3', '3 BHK'), ('4', '4 BHK'), ('5', '5 BHK'), ('6', '6 BHK'), ('7', '7 BHK'), ('8', '8 BHK'), ('9', '9 BHK'), ('10', '10 BHK'), ('11', '11 BHK'), ('12', '12 BHK'), ('13', '13 BHK'), ('14', '14 BHK'), ('15', '15 BHK')], max_length=6)),
                ('built_up_area', models.PositiveIntegerField(verbose_name='Built Up Area')),
                ('area_unit', models.CharField(choices=[('sq_ft', 'sq ft'), ('sq_yd', 'sq yd'), ('sq_mt', 'sq mt')], max_length=10)),
                ('furnish_type', models.CharField(choices=[('fully', 'Fully Furnished'), ('semi', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
