# Generated by Django 5.2.5 on 2025-09-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ac',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='chimney',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='cupboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='dining_table',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='fan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='gas_pipeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='geyser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='light',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='microwave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='modular_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='sofa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='stove',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='tv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='wardrobe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='washing_machine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='water_purifier',
            field=models.BooleanField(default=False),
        ),
    ]
