# Generated by Django 5.2.5 on 2025-09-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_property_ac_property_bed_property_chimney_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='CCTV',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='club_house',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='community_hall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='gated_community',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='housekeeping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='intercom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='kids_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='lift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='power_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='regular_water_supply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='security_guard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='sports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='visitor_parking',
            field=models.BooleanField(default=False),
        ),
    ]
