# Generated by Django 5.2.5 on 2025-10-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_property_cctv_property_club_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='locality',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
