# Generated by Django 5.2.5 on 2025-10-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
