# Generated by Django 5.2.5 on 2025-10-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_image',
            field=models.ImageField(blank=True, help_text='Uploaded Aadhaar card image', null=True, upload_to='aadhaar/'),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text="Aadhaar in format 'XXXX XXXX XXXX'", max_length=14, null=True, unique=True),
        ),
    ]
