# Generated by Django 5.2.5 on 2025-10-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_user_aadhaar_image_user_aadhaar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhaar_image',
            field=models.ImageField(blank=True, help_text='Uploaded Aadhaar card image', null=True, upload_to='aadhaars/'),
        ),
    ]
