# Generated by Django 5.2.5 on 2025-11-12 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rentnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.application')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
