# Generated by Django 5.2.5 on 2025-11-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rentalhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhaar_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='aadhaar_number',
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
