# Generated by Django 5.2.5 on 2025-11-14 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_user_aadhaar_image_remove_user_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_image',
            field=models.ImageField(blank=True, help_text='Uploaded Aadhaar image', null=True, upload_to='aadhaars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='XXXX XXXX XXXX', max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verification_pending', 'Verification pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PoliceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_aadhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('tenant_fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('tenant_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('landlord_aadhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('landlord_fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('landlord_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('verified', 'Verified'), ('unverified', 'Not verified')], max_length=16, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_request', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='police_verification', to='myapp.application')),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
    ]
